version: "3.8"
services:

  voting-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
